ci: update test target and action on push

diff --git a/.github/workflows/swift-xcode.yml b/.github/workflows/swift-xcode.yml
--- a/.github/workflows/swift-xcode.yml
+++ b/.github/workflows/swift-xcode.yml
@@ -8,7 +8,6 @@ on:
   pull_request:
     branches:
       - "main" 
-      - "develop"
 
 jobs:
   build:
@@ -76,10 +75,25 @@ jobs:
 
       - name: Run Tests
         env:
-          scheme: GoalsApp
+          scheme: GoalsTests
         run: |
           cd Application
           if [ $scheme = default ]; then scheme=$(cat default); fi
           if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild test -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" | xcpretty && exit ${PIPESTATUS[0]}
+          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" | xcpretty && exit ${PIPESTATUS[0]}
+
+      - name: Install slather
+        run: gem install slather
+
+      - name: Check Coverage
+        run: |
+          cd Application
+          slather coverage --scheme GoalsApp --workspace "$file_to_build" --output-directory ./coverage .
+          COVERAGE=$(grep -o 'Total Coverage: [0-9]*\.[0-9]*' ./coverage/index.html | grep -o '[0-9]*\.[0-9]*')
+          echo "Coverage is $COVERAGE%"
+          COVERAGE_INT=${COVERAGE%.*}
+          if [ "$COVERAGE_INT" -lt 80 ]; then
+            echo "Coverage is below 80%. Failing the build."
+            exit 1
+          fi
